sonar.projectKey=modul3-251511033
sonar.projectName=Modul 3 251511033 Ahmad Aisy Fathryan Siswandar
sonar.sources=app, routes, resources
sonar.exclusions=vendor/**, storage/**, bootstrap/cache/**, public/build/**
sonar.sourceEncoding=UTF-8